version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq
    # network_mode: host
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    networks:
      - pix-network
volumes:
  rabbitmq-volume:
networks:
  pix-network:
    external: true
